version: "3"
services:
  mros2_esp32:
    build:
      context: ./docker
      dockerfile: esp_idf.dockerfile
    container_name: esp_idf
    volumes:
      - ${MROS2_DIR}:/mros2-esp32
      - ${WORKSPACE}:/mros2-esp32/workspace/target
    devices:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - TARGET=${TARGET}
    command: ["/mros2-esp32/workspace/target/build.bash"]
    env_file:
      - .env